services:
  vfn-rag:
    build: .
    ports:
      - "80:80"
    environment:
      - AZURE_COSMOSDB_URI=${AZURE_COSMOSDB_URI}
      - AZURE_COSMOSDB_KEY=${AZURE_COSMOSDB_KEY}
      - AZURE_OPENAI_BASE=${AZURE_OPENAI_BASE}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_VERSION=${AZURE_OPENAI_VERSION}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - AZURE_OPENAI_EMBEDDING_MODEL=${AZURE_OPENAI_EMBEDDING_MODEL}
      - AZURE_EMBED_DEPLOYMENT_NAME=${AZURE_EMBED_DEPLOYMENT_NAME}

